# Generated by Django 5.2.5 on 2025-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
