# Generated by Django 5.2.5 on 2025-08-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
