# Generated by Django 5.2.5 on 2025-08-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_alter_customer_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseller',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
