# Generated by Django 5.2.5 on 2025-08-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_alter_reseller_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
