# Generated by Django 5.2.5 on 2025-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reseller_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
