# Generated by Django 5.2.5 on 2025-08-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_transaction_reseller_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-printed_at']},
        ),
    ]
