# Generated by Django 5.2.5 on 2025-08-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0012_remove_transaction_dealership_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyTransaction',
        ),
    ]
