# Generated by Django 5.2.5 on 2025-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0016_rename_date_created_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='invoice_header_color',
            field=models.CharField(default='#0064C8', help_text='Hex color code for invoice header', max_length=7),
        ),
    ]
