# Generated by Django 5.2.5 on 2025-08-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0017_businessprofile_invoice_header_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp']},
        ),
    ]
