# Generated by Django 5.2.5 on 2025-08-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0018_alter_expense_options_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Expense Categories'},
        ),
    ]
