# Generated by Django 5.2.5 on 2025-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0020_paymentcollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcollection',
            options={'ordering': ['-created_at']},
        ),
    ]
