# Generated by Django 5.2.5 on 2025-08-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0021_alter_paymentcollection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-date']},
        ),
    ]
