# Generated by Django 5.2.5 on 2025-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0022_alter_stocktake_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unique_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
