# Generated by Django 5.2.5 on 2025-08-27 08:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0024_alter_customer_account_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='paymentcollection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reseller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stocktake',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reseller_balance',
            new_name='dealership_price',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='invoice_header_color',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='paymentcollection',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='national_id_no',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='outstanding_balance',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='pos_app.transaction'),
        ),
        migrations.AddField(
            model_name='reseller',
            name='contact_info',
            field=models.CharField(default='No contact info', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.supplier'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(default='My Business', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(default='admin@business.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='legal_name',
            field=models.CharField(default='My Business Legal Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('ADMINISTRATIVE', 'Administrative'), ('MARKETING', 'Marketing'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SALARIES', 'Salaries'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='loss',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AlterField(
            model_name='loss',
            name='loss_type',
            field=models.CharField(choices=[('DAMAGE', 'Product Damage'), ('THEFT', 'Theft'), ('EXPIRY', 'Product Expiry'), ('WRITE_OFF', 'Write Off'), ('BAD_DEBT', 'Bad Debt'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='loss',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loss',
            name='total_loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('ONE_MONEY', 'One Money'), ('MUKURU', 'Mukuru'), ('INBUCKS', 'Inbucks'), ('MAMA_MONEY', 'Mama Money'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='collection_type',
            field=models.CharField(choices=[('CUSTOMER_DEBT', 'Customer Debt'), ('ITEM_TO_COLLECT', 'Item to Collect'), ('RESELLER_PAYMENT', 'Reseller Payment')], default='CUSTOMER_DEBT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_collections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unique_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profitlossreport',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profitlossreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profitlossreport',
            name='period_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=10),
        ),
        migrations.AlterField(
            model_name='profitlossreport',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('ONE_MONEY', 'One Money'), ('MUKURU', 'Mukuru'), ('INBUCKS', 'Inbucks'), ('MAMA_MONEY', 'Mama Money'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=15),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.transaction'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='name',
            field=models.CharField(default='Reseller Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='dealership_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.product'),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.reseller'),
        ),
        migrations.AlterField(
            model_name='resellersale',
            name='reseller_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='display_name',
            field=models.CharField(default='Staff Member', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('SALE', 'Sale'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='counted_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.product'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='system_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(default='No contact info', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='Supplier Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sale_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Product Received'), ('SOLD', 'Product Sold'), ('PAID_TO_COLLECT', 'Paid but to be Collected'), ('COLLECTED_TO_PAY', 'Collected but to Pay Later')], default='RECEIVED', max_length=20),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
