# Generated by Django 5.2.5 on 2025-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0025_remove_transactionitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_info',
            field=models.CharField(default='No contact info', max_length=200),
        ),
    ]
