# Generated by Django 5.2.5 on 2025-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0026_customer_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='account_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
