# Generated by Django 5.2.5 on 2025-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0030_alter_reseller_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='account_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
