# Generated by Django 5.2.5 on 2025-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0031_alter_reseller_account_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='reseller',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reseller',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reseller',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reseller',
            name='national_id_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reseller',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reseller',
            name='phone_no',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
