# Generated by Django 5.2.5 on 2025-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0032_remove_reseller_contact_info_reseller_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseller',
            options={'ordering': ['-id']},
        ),
    ]
