# Generated by Django 5.2.5 on 2025-08-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0034_transaction_payment_method_transactionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-printed_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
