# Generated by Django 5.2.5 on 2025-08-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0035_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-date']},
        ),
    ]
