# Generated by Django 5.2.5 on 2025-08-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0036_alter_stockmovement_options_alter_stocktake_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Expense Categories'},
        ),
    ]
