# Generated by Django 5.2.5 on 2025-08-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0037_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
