# Generated by Django 5.2.5 on 2025-08-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0038_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcollection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.invoice'),
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.transaction'),
        ),
    ]
