# Generated by Django 5.2.5 on 2025-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0041_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
