# Generated by Django 5.2.5 on 2025-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0042_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
