# Generated by Django 5.2.5 on 2025-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0045_staffprofile_can_access_reports_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['id']},
        ),
    ]
